apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-deployment
spec:
  selector:
    matchLabels:
      app: config-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-deployment
    spec:
      containers:
        - name: config
          image: gaspitas241/config
          ports:
            - containerPort: 8081