apiVersion: apps/v1
kind: Deployment
metadata:
  name: salida-deployment
  labels:
    app: salida-deployment
spec:
  selector:
    matchLabels:
      app: salida-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: salida-deployment
    spec:
      containers:
        - name: salida
          image: gaspitas241/salida
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: salida-service
  labels:
    app: salida-service
spec:
  selector:
    app: salida-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083